version: 2

models:
  - name: rep_sales_funnel_monthly
    description: "Monthly sales funnel analysis with 11 funnel steps"
    columns:
      - name: month
        description: "First day of the month for aggregation"
        tests:
          - not_null
          
      - name: kpi_name
        description: "Descriptive name of the funnel step"
        tests:
          - not_null
          
      - name: funnel_step
        description: "Numeric funnel step identifier"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 2.1, 3, 3.1, 4, 5, 6, 7, 8, 9]
              
      - name: deals_count
        description: "Number of deals at this funnel step"
        tests:
          - not_null